import type { Theme } from '../types';

export const themes: Record<string, Theme> = {
  default: {
    name: 'Default',
    body: 'bg-slate-900 text-slate-100',
    header: 'text-slate-100',
    buttonPrimary: 'bg-indigo-600 hover:bg-indigo-500 text-white',
    buttonSecondary: 'bg-slate-600 hover:bg-slate-500 text-white',
    buttonDanger: 'bg-red-600 hover:bg-red-500 text-white',
    buttonIconHoverBg: 'hover:bg-slate-700',
    buttonIconHoverText: 'hover:text-white',
    modalBg: 'bg-slate-800',
    modalText: 'text-slate-100',
    modalMutedText: 'text-slate-300',
    inputBg: 'bg-slate-700 border-slate-600 text-white',
    inputFocusRing: 'focus:ring-indigo-500 focus:border-indigo-500',
    columnBg: 'bg-slate-900/50',
    groupBg: 'bg-slate-800/80',
    linkBg: 'bg-slate-700/50',
    linkHoverBg: 'hover:bg-slate-700',
    linkText: 'text-slate-200',
    linkHoverText: 'hover:text-indigo-400',
    iconMuted: 'text-slate-400',
    ring: 'ring-indigo-500',
    dashedBorder: 'border-slate-700',
    textMuted: 'text-slate-400',
    textSubtle: 'text-slate-500',
    scrollbarTrack: '#1e293b',
    scrollbarThumb: '#475569',
    scrollbarThumbHover: '#64748b',
  },
  forest: {
    name: 'Forest',
    body: 'bg-gray-900 text-green-100',
    header: 'text-green-100',
    buttonPrimary: 'bg-emerald-700 hover:bg-emerald-600 text-white',
    buttonSecondary: 'bg-gray-600 hover:bg-gray-500 text-white',
    buttonDanger: 'bg-red-700 hover:bg-red-600 text-white',
    buttonIconHoverBg: 'hover:bg-gray-700',
    buttonIconHoverText: 'hover:text-white',
    modalBg: 'bg-gray-800',
    modalText: 'text-green-100',
    modalMutedText: 'text-gray-300',
    inputBg: 'bg-gray-700 border-gray-600 text-white',
    inputFocusRing: 'focus:ring-emerald-500 focus:border-emerald-500',
    columnBg: 'bg-gray-900/50',
    groupBg: 'bg-gray-800/80',
    linkBg: 'bg-gray-700/50',
    linkHoverBg: 'hover:bg-gray-700',
    linkText: 'text-green-200',
    linkHoverText: 'hover:text-emerald-400',
    iconMuted: 'text-gray-400',
    ring: 'ring-emerald-500',
    dashedBorder: 'border-gray-700',
    textMuted: 'text-gray-400',
    textSubtle: 'text-gray-500',
    scrollbarTrack: '#1f2937',
    scrollbarThumb: '#4b5563',
    scrollbarThumbHover: '#6b7280',
  },
  sunset: {
    name: 'Sunset',
    body: 'bg-stone-900 text-orange-100',
    header: 'text-orange-100',
    buttonPrimary: 'bg-amber-600 hover:bg-amber-500 text-white',
    buttonSecondary: 'bg-stone-600 hover:bg-stone-500 text-white',
    buttonDanger: 'bg-red-700 hover:bg-red-600 text-white',
    buttonIconHoverBg: 'hover:bg-stone-700',
    buttonIconHoverText: 'hover:text-white',
    modalBg: 'bg-stone-800',
    modalText: 'text-orange-100',
    modalMutedText: 'text-stone-300',
    inputBg: 'bg-stone-700 border-stone-600 text-white',
    inputFocusRing: 'focus:ring-amber-500 focus:border-amber-500',
    columnBg: 'bg-stone-900/50',
    groupBg: 'bg-stone-800/80',
    linkBg: 'bg-stone-700/50',
    linkHoverBg: 'hover:bg-stone-700',
    linkText: 'text-orange-200',
    linkHoverText: 'hover:text-amber-400',
    iconMuted: 'text-stone-400',
    ring: 'ring-amber-500',
    dashedBorder: 'border-stone-700',
    textMuted: 'text-stone-400',
    textSubtle: 'text-stone-500',
    scrollbarTrack: '#292524',
    scrollbarThumb: '#57534e',
    scrollbarThumbHover: '#78716c',
  },
  matrix: {
    name: 'Matrix',
    body: 'bg-black text-green-400 font-mono',
    header: 'text-green-400',
    buttonPrimary: 'bg-green-700/50 hover:bg-green-600/50 border border-green-500 text-green-300',
    buttonSecondary: 'bg-gray-700/50 hover:bg-gray-600/50 border border-gray-500 text-gray-300',
    buttonDanger: 'bg-red-700/50 hover:bg-red-600/50 border border-red-500 text-red-300',
    buttonIconHoverBg: 'hover:bg-gray-700',
    buttonIconHoverText: 'hover:text-white',
    modalBg: 'bg-black border border-green-700',
    modalText: 'text-green-400',
    modalMutedText: 'text-green-500',
    inputBg: 'bg-black border-green-700 text-green-300 placeholder-green-700',
    inputFocusRing: 'focus:ring-green-500 focus:border-green-500',
    columnBg: 'bg-black/50 border border-green-900',
    groupBg: 'bg-black/80 border border-green-800',
    linkBg: 'bg-black/50',
    linkHoverBg: 'hover:bg-green-900/50',
    linkText: 'text-green-400',
    linkHoverText: 'hover:text-green-300',
    iconMuted: 'text-green-600',
    ring: 'ring-green-500',
    dashedBorder: 'border-green-800',
    textMuted: 'text-green-500',
    textSubtle: 'text-green-600',
    scrollbarTrack: '#000000',
    scrollbarThumb: '#052e16',
    scrollbarThumbHover: '#14532d',
  },
  inferno: {
    name: 'Inferno',
    body: 'bg-red-950 text-yellow-200',
    header: 'text-yellow-200',
    buttonPrimary: 'bg-yellow-500 hover:bg-yellow-400 text-red-900',
    buttonSecondary: 'bg-red-800 hover:bg-red-700 text-yellow-100',
    buttonDanger: 'bg-orange-600 hover:bg-orange-500 text-white',
    buttonIconHoverBg: 'hover:bg-red-800',
    buttonIconHoverText: 'hover:text-yellow-100',
    modalBg: 'bg-red-900',
    modalText: 'text-yellow-100',
    modalMutedText: 'text-yellow-300',
    inputBg: 'bg-red-800 border-red-700 text-yellow-100',
    inputFocusRing: 'focus:ring-yellow-500 focus:border-yellow-500',
    columnBg: 'bg-red-950/50',
    groupBg: 'bg-red-900/80',
    linkBg: 'bg-red-800/50',
    linkHoverBg: 'hover:bg-red-800',
    linkText: 'text-yellow-200',
    linkHoverText: 'hover:text-yellow-400',
    iconMuted: 'text-yellow-500',
    ring: 'ring-yellow-500',
    dashedBorder: 'border-red-800',
    textMuted: 'text-yellow-400',
    textSubtle: 'text-yellow-600',
    scrollbarTrack: '#450a0a',
    scrollbarThumb: '#7f1d1d',
    scrollbarThumbHover: '#b91c1c',
  },
  ocean: {
    name: 'Ocean',
    body: 'bg-blue-950 text-cyan-100',
    header: 'text-cyan-100',
    buttonPrimary: 'bg-cyan-600 hover:bg-cyan-500 text-white',
    buttonSecondary: 'bg-blue-800 hover:bg-blue-700 text-cyan-100',
    buttonDanger: 'bg-rose-600 hover:bg-rose-500 text-white',
    buttonIconHoverBg: 'hover:bg-blue-800',
    buttonIconHoverText: 'hover:text-white',
    modalBg: 'bg-blue-900',
    modalText: 'text-cyan-100',
    modalMutedText: 'text-cyan-300',
    inputBg: 'bg-blue-800 border-blue-700 text-white',
    inputFocusRing: 'focus:ring-cyan-500 focus:border-cyan-500',
    columnBg: 'bg-blue-950/50',
    groupBg: 'bg-blue-900/80',
    linkBg: 'bg-blue-800/50',
    linkHoverBg: 'hover:bg-blue-800',
    linkText: 'text-cyan-200',
    linkHoverText: 'hover:text-cyan-400',
    iconMuted: 'text-cyan-400',
    ring: 'ring-cyan-500',
    dashedBorder: 'border-blue-800',
    textMuted: 'text-cyan-400',
    textSubtle: 'text-cyan-500',
    scrollbarTrack: '#172554',
    scrollbarThumb: '#1e3a8a',
    scrollbarThumbHover: '#1e40af',
  },
  arctic: {
    name: 'Arctic',
    body: 'bg-slate-100 text-slate-800',
    header: 'text-slate-900',
    buttonPrimary: 'bg-blue-600 hover:bg-blue-500 text-white',
    buttonSecondary: 'bg-slate-300 hover:bg-slate-400 text-slate-800',
    buttonDanger: 'bg-red-500 hover:bg-red-600 text-white',
    buttonIconHoverBg: 'hover:bg-slate-300',
    buttonIconHoverText: 'hover:text-slate-900',
    modalBg: 'bg-white',
    modalText: 'text-slate-900',
    modalMutedText: 'text-slate-600',
    inputBg: 'bg-white border-slate-300 text-slate-900',
    inputFocusRing: 'focus:ring-blue-500 focus:border-blue-500',
    columnBg: 'bg-slate-100/50',
    groupBg: 'bg-slate-200/80',
    linkBg: 'bg-white/50',
    linkHoverBg: 'hover:bg-blue-100',
    linkText: 'text-slate-700',
    linkHoverText: 'hover:text-blue-600',
    iconMuted: 'text-slate-500',
    ring: 'ring-blue-500',
    dashedBorder: 'border-slate-300',
    textMuted: 'text-slate-500',
    textSubtle: 'text-slate-400',
    scrollbarTrack: '#e2e8f0',
    scrollbarThumb: '#cbd5e1',
    scrollbarThumbHover: '#94a3b8',
  },
  synthwave: {
    name: 'Synthwave',
    body: 'bg-indigo-950 text-pink-200',
    header: 'text-pink-200',
    buttonPrimary: 'bg-pink-600 hover:bg-pink-500 text-white',
    buttonSecondary: 'bg-purple-800 hover:bg-purple-700 text-pink-100',
    buttonDanger: 'bg-rose-600 hover:bg-rose-500 text-white',
    buttonIconHoverBg: 'hover:bg-purple-800',
    buttonIconHoverText: 'hover:text-white',
    modalBg: 'bg-indigo-900',
    modalText: 'text-pink-100',
    modalMutedText: 'text-pink-300',
    inputBg: 'bg-purple-900 border-purple-800 text-white',
    inputFocusRing: 'focus:ring-cyan-400 focus:border-cyan-400',
    columnBg: 'bg-indigo-950/50',
    groupBg: 'bg-indigo-900/80',
    linkBg: 'bg-purple-900/50',
    linkHoverBg: 'hover:bg-purple-900',
    linkText: 'text-pink-200',
    linkHoverText: 'hover:text-cyan-300',
    iconMuted: 'text-pink-400',
    ring: 'ring-cyan-400',
    dashedBorder: 'border-purple-800',
    textMuted: 'text-pink-400',
    textSubtle: 'text-purple-400',
    scrollbarTrack: '#281c5a',
    scrollbarThumb: '#4338ca',
    scrollbarThumbHover: '#4f46e5',
  },
};
